### ISSUE TITLE
Bug: `codefresh wait` broken in v0.15.1

### ISSUE THREAD

**Issue by LingJesse** [codefresh-io/cli#291]
FYI that the v0.15.1 release seems to have broken the wait command.

Steps to reproduce:
1. Execute `codefresh wait $process_id`
2. Returns `Error: SDK has no handler for path: 'workflows.waitForStatus'. Please check the openapi.json used for sdk`

**Comment by itai-codefresh** [comment]
Hey there.
Can you please run the command with DEBUG mode enabled?
`DEBUG=codefresh* codefresh wait $process_id`

**Comment by LingJesse** [comment]
Sure thing!
```Error: SDK has no handler for path: 'workflows.waitForStatus'. Please check the openapi.json used for sdk
    at Client.resolve (/snapshot/cli/node_modules/codefresh-sdk/lib/Client.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by itai-codefresh** [comment]
Can you please copy the entire output of the execution? you should see more debug information like the following:
```
Itais-MacBook-Pro:cli itaigendler$ DEBUG=codefresh* codefresh wait $$$
  codefresh:sdk:logic apis: { clusters: Clusters { sdk: {} },
  codefresh:sdk:logic   logs: Logs { sdk: {} },
  codefresh:sdk:logic   workflows: Workflows { sdk: {} } } +0ms
  codefresh:sdk:logic logic path: workflows.waitForStatus +43ms
  codefresh:sdk:logic logic path: workflows.sdk +2ms
  codefresh:sdk:http http created: { timeout: 30000, maxAttempts: 10, retryDelay: 500, retryStrategy: [Function: RETRY_STRATEGY] } +0ms
  codefresh:sdk:client loading spec: { forceRefresh: false, disableCache: undefined, specUrl: undefined } +0ms
  codefresh:sdk:cache reading spec from cache: openapi-2019-02-12.json +0ms
  codefresh:sdk:client using provided server url:  https://g.codefresh.io/api +108ms
```
How did you install the cli?

**Comment by LingJesse** [comment]
Yup! Here you go. cli was installed via brew. Was working until brew upgraded the version today.
`codefresh:sdk:logic apis: {} +0ms
  codefresh:sdk:http http created: { timeout: 30000, maxAttempts: 10, retryDelay: 500, retryStrategy: [Function: RETRY_STRATEGY] } +0ms
  codefresh:sdk:client loading spec: { forceRefresh: false, disableCache: undefined, specUrl: undefined } +0ms
  codefresh:sdk:cache reading spec from cache: openapi-2019-02-12.json +0ms
  codefresh:sdk:client using provided server url:  https://g.codefresh.io/api +88ms
  codefresh:sdk:client:post-process apis: { abac:
  codefresh:sdk:client:post-process    { rules:
  codefresh:sdk:client:post-process       { list: [Function],
  codefresh:sdk:client:post-process         create: [Function],
  codefresh:sdk:client:post-process         createOrDelete: [Function],
  codefresh:sdk:client:post-process         listByResource: [Function],
  codefresh:sdk:client:post-process         tags: [Object],
  codefresh:sdk:client:post-process         listByTeam: [Function],
  codefresh:sdk:client:post-process         createInBatch: [Function],
  codefresh:sdk:client:post-process         delete: [Function],
  codefresh:sdk:client:post-process         get: [Function] } },
  codefresh:sdk:client:post-process   accounts:
  codefresh:sdk:client:post-process    { deleteUserFromAccount: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      addExistingUserToAccount: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      deleteAdmin: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      setAsAdmin: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      addUserToAccount: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      updateAccountPublicSettings: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      updateUserDetails: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getUsersForAccount: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      listAccounts: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      addAccount: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      addPendingUserWithoutAccount: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      deleteAccount: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getById: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      updateAccount: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   onPrem:
  codefresh:sdk:client:post-process    { runtimeEnvs:
  codefresh:sdk:client:post-process       { list: [Function],
  codefresh:sdk:client:post-process         plan: [Object],
  codefresh:sdk:client:post-process         account: [Object],
  codefresh:sdk:client:post-process         system: [Object] } },
  codefresh:sdk:client:post-process   tokens:
  codefresh:sdk:client:post-process    { generate: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      list: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   builds:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      rebuild: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   workflows:
  codefresh:sdk:client:post-process    { restart: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      update: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      buildByService: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      service: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   clusters:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   compositions:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      create: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      launch: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      update: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      patch: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      duplicate: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   contexts:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      create: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      replace: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      patch: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   envs:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      terminateAll: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      pause: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      rename: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      start: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      status: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      stop: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      terminate: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      unpause: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   features: { account: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   helm:
  codefresh:sdk:client:post-process    { boards:
  codefresh:sdk:client:post-process       { deleteAll: [Function],
  codefresh:sdk:client:post-process         list: [Function],
  codefresh:sdk:client:post-process         create: [Function],
  codefresh:sdk:client:post-process         getByName: [Function],
  codefresh:sdk:client:post-process         delete: [Function],
  codefresh:sdk:client:post-process         get: [Function],
  codefresh:sdk:client:post-process         patch: [Function],
  codefresh:sdk:client:post-process         update: [Function] },
  codefresh:sdk:client:post-process      sections:
  codefresh:sdk:client:post-process       { create: [Function],
  codefresh:sdk:client:post-process         reorder: [Function],
  codefresh:sdk:client:post-process         delete: [Function],
  codefresh:sdk:client:post-process         get: [Function],
  codefresh:sdk:client:post-process         patch: [Function],
  codefresh:sdk:client:post-process         update: [Function],
  codefresh:sdk:client:post-process         deleteAll: [Function],
  codefresh:sdk:client:post-process         list: [Function],
  codefresh:sdk:client:post-process         getByName: [Function] },
  codefresh:sdk:client:post-process      repos:
  codefresh:sdk:client:post-process       { create: [Function],
  codefresh:sdk:client:post-process         list: [Function],
  codefresh:sdk:client:post-process         delete: [Function],
  codefresh:sdk:client:post-process         update: [Function],
  codefresh:sdk:client:post-process         get: [Function] },
  codefresh:sdk:client:post-process      releases: { delete: [Function], test: [Function] },
  codefresh:sdk:client:post-process      charts: { install: [Function], promote: [Function] } },
  codefresh:sdk:client:post-process   triggers:
  codefresh:sdk:client:post-process    { events:
  codefresh:sdk:client:post-process       { create: [Function],
  codefresh:sdk:client:post-process         list: [Function],
  codefresh:sdk:client:post-process         get: [Function],
  codefresh:sdk:client:post-process         delete: [Function] },
  codefresh:sdk:client:post-process      list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getEventTriggers: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getPipelineTriggers: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      create: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      types: { list: [Function], get: [Function] } },
  codefresh:sdk:client:post-process   version:
  codefresh:sdk:client:post-process    { getHermesVersion: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getNomiosVersion: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getServerVersion: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   images:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      addFromExternalSource: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getTags: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      tag: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      untag: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getMetadata: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      upsertMetadata: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      deleteMetadata: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   kubernetes: { generateImagePullSecret: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   payments:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      create: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getPlans: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   pipelines:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      create: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      run: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      validateYaml: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      replace: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   progress:
  codefresh:sdk:client:post-process    { download: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      terminate: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   providers: { githubHook: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   'Codefresh Registry': { generateCfcrToken: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   repos:
  codefresh:sdk:client:post-process    { git: { list: [Function], get: [Function] },
  codefresh:sdk:client:post-process      list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      getSettings: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      create: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   registries:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      create: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      test: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   runtimeEnvs:
  codefresh:sdk:client:post-process    { list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      setDefault: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      update: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      delete: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      get: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   runtime: { launch: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   teams:
  codefresh:sdk:client:post-process    { create: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      list: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      synchronizeClientWithGroup: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      addUser: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      removeUser: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      listByUser: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   users:
  codefresh:sdk:client:post-process    { get: { [Function] spec: [Object] },
  codefresh:sdk:client:post-process      changeAccount: { [Function] spec: [Object] } },
  codefresh:sdk:client:post-process   firebase: { getToken: { [Function] spec: [Object] } } } +0ms
  codefresh:sdk:client client loaded! +19ms
  codefresh:sdk:client sdk path: workflows.waitForStatus +0ms
  codefresh:sdk:client args: [ 1231234, 'success', moment("2019-02-12T16:22:04.278"), 'codefresh*' ] +0ms
  codefresh:sdk:client no handler for path: workflows.waitForStatus +2ms
(node:31104) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
Error: SDK has no handler for path: 'workflows.waitForStatus'. Please check the openapi.json used for sdk
    at Client.resolve (/snapshot/cli/node_modules/codefresh-sdk/lib/Client.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by itai-codefresh** [comment]
The issue was resolved in this pr: https://github.com/codefresh-io/cli/pull/292
Please update to the newest version.

Sorry for any inconvenience.
