### ISSUE TITLE
Autocomplete `create pipeline` doesn't resolve

### ISSUE THREAD

**Issue by msheiny** [codefresh-io/cli#301]
```bash
$ codefresh version 
client version: 0.16.7

$ zsh --version
zsh 5.3.1 (x86_64-debian-linux-gnu)
```

```bash
$ codefresh create <tab>
board                 composition           helm-repo             runtime-environments  teams                 trigger
clusters              context               registry              section               token                 trigger-event
```
The `create pipeline` is missing from the autocompletion script logic for me. Let me know what other data points I can provide to assist with debugging here. Or maybe this is as designed completion logic?

Thanks!

**Comment by olegsu** [comment]
@msheiny , thanks, we will check that

**Comment by msheiny** [comment]
i see a bunch of references to it thou @olegsu :

**Comment by msheiny** [comment]
Also this blog post https://codefresh.io/devops-tutorial/programmatic-creation-codefresh-pipelines-part1/ lead me to believe that command existed :)

**Comment by olegsu** [comment]
Thanks @msheiny , will make sure to fix the bp and the repo!
@kostis-codefresh

**Comment by kostis-codefresh** [comment]
@msheiny I updated the blog post with the correct pipeline spec (it wasn't valid with the latest Codefresh platform).

Regarding the create command make sure that you have the latest version of the Codefresh CLI - 0.35.0 at the time or writing - and the command mentioned in the blog post should work just fine.

(Actually both `codefresh create pipeline -f spec.yml` **and** `codefresh create -f spec.yml` should work)
