### ISSUE TITLE
Unable to authenticate 

### ISSUE THREAD

**Issue by msheiny** [codefresh-io/cli#306]
After a day or so gap from using the codefresh cli tooling I'm no longer able to authenticate. I continually get this error:

`Error: Error: Please create or update your authentication context; caused by Error: "{\"status\":401,\"code\":\"2401\",\"name\":\"UNAUTHORIZED_ERROR\",\"message\":\"Unauthorized\",\"context\":{}}"`

Okay thats fine, lets look at my contexts:
```
╰─$ codefresh auth get-contexts                                                            
CURRENT NAME                                 URL                    ACCOUNT STATUS 
*       a_________________________________ https://g.codefresh.io         Revoked
        b_________________________________ https://g.codefresh.io         Revoked                      
*       default                              https://g.codefresh.io msheiny Valid 
        c__________________________________ https://g.codefresh.io         Revoked
```

That's weird . None of my tokens are revoked in the UX. So.. I tried two things, first I updated the context using the `codefresh auth create-context --api-key {API_KEY}` and I set the context to that one.

```bash
$ codefresh auth create-context --api-key $(cat ./cfkey)                                                                                                                                          
Updated context: default                                                  
Switched to context: default                                                                                                                                                                                      

$ codefresh auth get-contexts                                                                         
CURRENT NAME                                 URL                    ACCOUNT STATUS
*       a__________________________________ https://g.codefresh.io         Revoked
        b__________________________________ https://g.codefresh.io         Revoked
*       default                              https://g.codefresh.io msheiny Valid  
        c__________________________________ https://g.codefresh.io         Revoked
```

That's really weird.. no change. So I go to manually edit ~/.cfconfig. ... I get frustrated and just clear the dang thing out completely. When I do a list contexts I still get:

```
$ cat ~/.cfconfig            
contexts: {}
current-context: ''
$ codefresh auth get-contexts
CURRENT NAME                                 URL                    ACCOUNT STATUS
*       ____________________________ https://g.codefresh.io         Revoked
```

I'm super confused. Can someone shed light on this issue? I'm on cli version `0.17.3` (upgraded to see if it would fix my issue).

**Comment by itai-codefresh** [comment]
hey @msheiny.
can you please share the following:
1. how did you install the cli
2. your operation system details

**Comment by msheiny** [comment]
Hi @itai-codefresh !  So to update, I ended up power cycling between work sessions. Now that I have returned .. the mysterious context in my config seems to be working again. I'm super perplexed. For a little background. 

1 - I installed the CLI via the tar ball extracted to my $PATH
2 - I'm running debian `stretch`, x86_64. Shell is zsh `5.3.1`
3 - I've confirmed that this environment variable is not set

I guess I can close this issue for my sake because I can't reproduce. I'll re-open if I re-encounter?

Thanks!

**Comment by yaroslav-codefresh** [comment]
Hi, @msheiny!
Is it possible that `$CF_API_KEY` environment variable was set in your session?

**Comment by msheiny** [comment]
Hey @yaroslav-codefresh .... you are right!  I utilize a cloudflare tool that has the same env var: https://github.com/cloudflare/python-cloudflare

That's not your fault there is a env var conflict .... but this was super frustrating. I'll leave it up to your team if this is something you think is worth addressing. For new comers they might be able to find this ticket :)

Maybe at least on the show context command you indicated that the key is coming in from an env var?
