### ISSUE TITLE
codefresh validate should return non-zero exit codes on validation

### ISSUE THREAD

**Issue by todaywasawesome** [codefresh-io/cli#367]
> Codefresh CLI’s codefresh validate <filename> returns 0 even when the file is not valid. It should return non-zero so I can use it in continuous integration without having to do fancy grep-ing.

![](https://aws1.discourse-cdn.com/business5/uploads/codefreshtest/original/1X/cbfa1339b7b4a2a71b09f63cac898838fdaf0b54.png)

Discussion https://community.codefresh.io/t/codefresh-cli-validate-returns-0-even-when-invalid/250

**Comment by RothAndrew** [comment]
Thanks @todaywasawesome !

**Comment by kostis-codefresh** [comment]
Should be fixed by PR https://github.com/codefresh-io/cli/pull/368
