### ISSUE TITLE
[bug] On codefresh run

### ISSUE THREAD

**Issue by JulienBreux** [codefresh-io/cli#405]
Hi!

When I run `codefresh run xxxx -v foo=bar`, the job is executed but the feedback of the CLI is:

```
node(48430,0x10b647dc0) malloc: can't allocate region
*** mach_vm_map(size=7205759404077146112) failed (error code=3)
node(48430,0x10b647dc0) malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
[1]    48430 abort      codefresh run xxxx -v foo=bar
```

**Comment by AlvinKudos** [comment]
In my case, running `codefresh run` with node v12 and v14 fails.  `codefresh run` works with node v10.20.1.

I see multiple types of error messages including `Segmentation fault: 11`.

**Comment by SpainTrain** [comment]
> In my case, running `codefresh run` with node v12 and v14 fails. `codefresh run` works with node v10.20.1.

I can corroborate - on Ubuntu `codefresh run` on node 12.x fails with allocation errors / segfault, works on node 10.x

**Comment by oren-codefresh** [comment]
Fixed
