### ISSUE TITLE
Typo in --help output

### ISSUE THREAD

**Issue by jordan-rash** [codefresh-io/cli#440]
See here: https://github.com/codefresh-io/cli/blob/412202bbf28837a6d655ea849762a36593aaa829/lib/interface/cli/commands/analyzer/analyze.cmd.js#L8

Codefresh is spelled "Cofefresh"

**Comment by roi-codefresh** [comment]
@jordan-rash thanks, this was fixed in https://github.com/codefresh-io/cli/commit/4d348f80da5e9adc44e67e258b4fe0eacfe5c9dc.
