### ISSUE TITLE
Error: Runner installation failed: ENOENT: no such file or directory, chmod '~/.Codefresh/agent/venona'

### ISSUE THREAD

**Issue by guillaumemaka** [codefresh-io/cli#477]
Hi, 

when I try to setup a runner `codefresh runner init --token xxxx`  I got this error:
```
Error: Runner installation failed: ENOENT: no such file or directory, chmod '~/.Codefresh/agent/venona'
```

Codefresh CLI client version: 0.64.0
Install Mode: yarn
OS: Mac OS Catalina Version 10.15.5 (19F96)

**Comment by oren-codefresh** [comment]
Hi @guillaumemaka 
Can you please update your codefresh cli , we believe that this issue was fixed a while ago
Thanks
Oren.
