### ISSUE TITLE
How do we actually use the --tolerations flag on the CLI?

### ISSUE THREAD

**Issue by rcollier-goodrx** [codefresh-io/cli#558]
I have a tolerations.json file with the following contents:

```
[{
	"effect": "NoSchedule",
	"key": "pool",
	"operator": "Equal",
	"value": "true"
}]
```

When I run the cli using the following command.

```
codefresh init --tolerations tolerations.json
```

I get the following error.

```
Error: can not parse tolerations: invalid character 'o' in literal true (expecting 'r')
Error: Failed to install new agent: Component exited with status code 1
```

Any examples you could provide would be helpful. Thanks

**Comment by rcollier-goodrx** [comment]
I see that the docs say to prefix the file with `@` but that doesn't seem to work either.

**Comment by talal7860** [comment]
@rcollier-goodrx Did you find the solution?

**Comment by oren-codefresh** [comment]
We pushed a fix @talal7860 @rcollier-goodrx , if you want to use a file as your tolerations file please use --tolerations @tolerations.json

**Comment by talal7860** [comment]
Thanks @oren-codefresh, can we update an existing runner with a similar command?

**Comment by talal7860** [comment]
@oren-codefresh , I tried, still same issue, installed the latest version from npm

**Comment by oren-codefresh** [comment]
@talal7860 Can you please share the command line that you used and the tolerations file as well

**Comment by talal7860** [comment]
```bash
codefresh runner init \
  --name=codefresh-runner\
  --kube-context-name=staging\
  --set-default-runtime=false\
  --kube-namespace="codefresh"\
  --exec-demo-pipeline=true\
  --tolerations=codefresh-tolerations.json\
  --set-value=Storage.Backend=ebs \
  --set-value=Storage.Encrypted=true\
  --set-value=Storage.AvailabilityZone=ca-central-1a
```
codefresh-tolerations.json
```json
[{
  "effect": "NoSchedule",
  "key": "codefresh.io",
  "value": "engine"
}]
```

**Comment by oren-codefresh** [comment]
@talal7860  , please change the command to : --tolerations=**@**codefresh-tolerations.json\
